[build]
  # Указываем что нужно собирать веб-приложение
  base = "apps/web"
  command = "npm install && npm run build"
  publish = ".next"

[build.environment]
  # Node.js версия
  NODE_VERSION = "18"
  # NPM версия
  NPM_VERSION = "9"
  # Node.js окружение
  NODE_ENV = "production"
  # Включаем экспорт статики
  NEXT_PUBLIC_NETLIFY_DEPLOY = "true"
  # Demo режим для Netlify
  NEXT_PUBLIC_DEMO_MODE = "true"

# Настройки для SPA маршрутизации Next.js
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Настройки кеширования
[[headers]]
  for = "/static/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/*.js"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/*.css"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

# Настройки безопасности
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "origin-when-cross-origin"
    X-XSS-Protection = "1; mode=block"

[[plugins]]
  package = "@netlify/plugin-nextjs"

[dev]
  command = "npm run dev"
  port = 3000
  targetPort = 3000
  autoLaunch = false 